### ISSUE TITLE
感谢开源，在运行过程中遇到如下异常后，程序不在执行

### ISSUE THREAD

**Issue by imlinda** [MaoYanFi/zoon-battle#1]
希望可以在遇到异常后继续重复执行

```
\zoon-battle\node_modules\web3-core-helpers\lib\errors.js:87
        var error = new Error(message);
                    ^

Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0x7347861878126216a7e1f270050d3e7a09bdddc86d92d225a2825ad0fde29817",
  "blockNumber": 10216456,
  "contractAddress": null,
  "cumulativeGasUsed": 8421943,
  "from": "0xbc06ab9d4994b182bfb0ea51ae97fd2549eb5856",
  "gasUsed": 91080,
  "logs": [],
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0xf70c08a428f300c7f3e3f09217211d21f7a50410",
  "transactionHash": "0x76fbaf19b42fabcae956296ed7519858d2a1035df6a7a43d219ab5c61598ee59",
  "transactionIndex": 60,
  "type": "0x0"
}
    at Object.TransactionError (\zoon-battle\node_modules\web3-core-helpers\lib\errors.js:87:21)
    at Object.TransactionRevertedWithoutReasonError (\zoon-battle\node_modules\web3-core-helpers\lib\errors.js:98:21)
    at \zoon-battle\node_modules\web3-core-method\lib\index.js:393:57
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  receipt: {
    blockHash: '0x7347861878126216a7e1f270050d3e7a09bdddc86d92d225a2825ad0fde29817',
    blockNumber: 10216456,
    contractAddress: null,
    cumulativeGasUsed: 8421943,
    from: '0xbc06ab9d4994b182bfb0ea51ae97fd2549eb5856',
    gasUsed: 91080,
    logs: [],
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    status: false,
    to: '0xf70c08a428f300c7f3e3f09217211d21f7a50410',
    transactionHash: '0x76fbaf19b42fabcae956296ed7519858d2a1035df6a7a43d219ab5c61598ee59',
    transactionIndex: 60,
    type: '0x0'
  }
}
```

**Comment by steeleader** [comment]
看你的交易，报错： Fail with error 'reach limit times battle'

你是不是跑了两个进程？

**Comment by imlinda** [comment]
有可能 我关掉试试

**Comment by imlinda** [comment]
关掉多余进程后可以了 没有报错了
